#
# Licensed to the Apache Software Foundation (ASF) under one or more
# contributor license agreements.  See the NOTICE file distributed with
# this work for additional information regarding copyright ownership.
# The ASF licenses this file to You under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License.  You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

# Default values for celeborn.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# we provide a default celeborn image, you can also replace to your image
releaseVersion: 0.4.0.9

image:
  repository: docker-reg.devops.xiaohongshu.com/data/celeborn
  master:
    pullPolicy: Always
    tag: 0.4.0.9
  worker:
    pullPolicy: Always
    tag: 0.4.0.9


imagePullSecrets:
  - name: xhs-docker-registry

# master replicas should not less than 3
masterReplicas: 3
# worker replicas set on demand, should less than node number
workerReplicas: 20

partition:
  master: 0
  worker: 0

network:
  master:
    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"
  worker:
    hostNetwork: true
    dnsPolicy: "ClusterFirstWithHostNet"

pvc:
  master:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "csi-local-host-path"
    resources:
      requests:
        storage: 300Gi
  worker:
    accessModes: [ "ReadWriteOnce" ]
    storageClassName: "csi-local-host-path"
    resources:
      requests:
        storage: 1.8Ti

securityContext:
  runAsUser: 10006
  runAsGroup: 10006
  fsGroup: 10006

masterHosts: 10.144.10.165,10.144.10.178,10.144.10.179


# Current Celeborn support followings volume type:
# - emptyDir
# - hostPath
# Note:
# hostPath only works in hostPath type using to set `volumes hostPath path`
# Celeborn Master will pick first volumes for store raft log
# diskType only works in Celeborn Worker with hostPath type to manifest local disk type
volumes:
  master:
    - mountPath: /data/celeborn
      hostPath: /data
      type: hostPath
  worker:
    - mountPath: /data/celeborn
      hostPath: /data
      type: hostPath


# celeborn configurations
celeborn:
  celeborn.rpc.io.mode: NIO
  celeborn.rpc.io.clientThreads: 8
  celeborn.rpc.io.serverThreads: 8
  celeborn.rpc.io.numConnectionsPerPeer: 8
  celeborn.push.io.numConnectionsPerPeer: 8
  celeborn.worker.flusher.buffer.size: 256k
  celeborn.metrics.enabled: true
  celeborn.worker.monitor.disk.enabled: true
  celeborn.worker.directMemoryRatioToPauseReceive: 0.9
  celeborn.worker.directMemoryRatioToResume: 0.85
  celeborn.worker.graceful.shutdown.enabled: true
  celeborn.worker.fetch.io.threads: 64
  celeborn.worker.push.io.threads: 64
  celeborn.worker.replicate.io.threads: 64
  celeborn.worker.flusher.threads: 64
  celeborn.worker.writer.close.timeout: 590s
  celeborn.worker.commitFiles.timeout: 600s
  celeborn.worker.storage.disk.reserve.size: 100G
  celeborn.worker.decommission.forceExitTimeout: 24h
  celeborn.master.ha.enabled: true


podExtraLabels:
  sd.xhs.com/service: xhs.data.emr-k8s.rss-k8s
  xhs.com/prdline: data
  sd.xhs.data.com/service: redspark

environments:
  CELEBORN_MASTER_MEMORY: 48g
  CELEBORN_WORKER_MEMORY: 8g
  CELEBORN_WORKER_OFFHEAP_MEMORY: 40g
  CELEBORN_NO_DAEMONIZE: 1
  JAVA_HOME: /opt/jdk-17.0.9+9
  CELEBORN_PREFER_JEMALLOC: true
  CELEBORN_JEMALLOC_PATH: /usr/lib64/libjemalloc.so.2
  MALLOC_CONF: tcache:false,dirty_decay_ms:5000,narenas:4,background_thread:true
  TZ: "Asia/Shanghai"


podMonitor:
  enable: false
  podMetricsEndpoint:
    scheme: http
    interval: 5s
    portName: metrics

service:
  type: ClusterIP
  port: 9197

portMapping:
  # 默认组 9097 的端口配置
  "9097":
    master: 9097
    ratis: 9072
    worker_fetch: 9092
    worker_rpc: 9093
    worker_push: 9094
    worker_replicate: 9095
    metrics_master: 9098
    metrics_worker: 9096

  # 组 9197 的端口配置（示例）
  "9197":
    master: 9197
    ratis: 9172
    worker_fetch: 9192
    worker_rpc: 9193
    worker_push: 9194
    worker_replicate: 9195
    metrics_master: 9198
    metrics_worker: 9196

  # 组 9297 的端口配置（示例）
  "9297":
    master: 9297
    ratis: 9272
    worker_fetch: 9292
    worker_rpc: 9293
    worker_push: 9294
    worker_replicate: 9295
    metrics_master: 9298
    metrics_worker: 9296


cluster:
  name: cluster


resources:
  master:
    limits:
      cpu: 8
      memory: 64Gi
    requests:
      cpu: 8
      memory: 64Gi
  worker:
    limits:
      cpu: 8
      memory: 64Gi
    requests:
      cpu: 8
      memory: 64Gi

# priorityClass used for Celeborn pods
priorityClass:
  master:
    # Specifies whether a priorityClass should be created
    create: true
    # Specifies priorityClass name to be used (created if `create: true`)
    name: ~
    # half of system-cluster-critical by default
    value: 1000000000

  worker:
    create: true
    name: ~
    # celeborn master minus 1000
    value: 999999000


tolerations:
  master:
    - key: "dedicate"
      operator: "Equal"
      value: "spark-master"
      effect: "NoSchedule"
  worker: []

nodeSelector:
  master:
    dedicate: spark-master
  worker:
    dedicate: task

