/*
 * Licensed to the Apache Software Foundation (ASF) under one or more
 * contributor license agreements.  See the NOTICE file distributed with
 * this work for additional information regarding copyright ownership.
 * The ASF licenses this file to You under the Apache License, Version 2.0
 * (the "License"); you may not use this file except in compliance with
 * the License.  You may obtain a copy of the License at
 *
 *    http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package org.apache.celeborn.build

import java.io.File

import sbt._
import sbt.Keys._
import sbtprotoc.ProtocPlugin.autoImport._

/**
 * This plugin generates CelebornBuildInfo.scala at compile time with version information.
 * This is used for sbt build.
 */
object CelebornBuildInfoPlugin extends AutoPlugin {
  override def trigger = noTrigger

  object autoImport {
    val generateBuildInfo = taskKey[Seq[File]]("Generate CelebornBuildInfo.scala")
  }

  import autoImport._

  override lazy val projectSettings: Seq[Setting[_]] = Seq(
    generateBuildInfo := (Def.task {
      val log = streams.value.log
      val targetDir = (Compile / sourceManaged).value / "org" / "apache" / "celeborn" / "common"
      val targetFile = targetDir / "CelebornBuildInfo.scala"

      // Get version information
      val celebornVersion = version.value

      log.info(s"Generating CelebornBuildInfo with version: $celebornVersion")
      
      // Ensure the target directory exists before writing
      if (!targetDir.exists()) {
        log.info(s"Creating directory: $targetDir")
        IO.createDirectory(targetDir)
      }

      val content =
        s"""/*
           | * Licensed to the Apache Software Foundation (ASF) under one or more
           | * contributor license agreements.  See the NOTICE file distributed with
           | * this work for additional information regarding copyright ownership.
           | * The ASF licenses this file to You under the Apache License, Version 2.0
           | * (the "License"); you may not use this file except in compliance with
           | * the License.  You may obtain a copy of the License at
           | *
           | *    http://www.apache.org/licenses/LICENSE-2.0
           | *
           | * Unless required by applicable law or agreed to in writing, software
           | * distributed under the License is distributed on an "AS IS" BASIS,
           | * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
           | * See the License for the specific language governing permissions and
           | * limitations under the License.
           | */
           |
           |package org.apache.celeborn.common
           |
           |/**
           | * This object provides version information for Celeborn.
           | * The values are automatically generated during the build process.
           | *
           | * DO NOT EDIT MANUALLY - This file is auto-generated by CelebornBuildInfoPlugin
           | */
           |private[celeborn] object CelebornBuildInfo {
           |  val celebornVersion: String = "$celebornVersion"
           |
           |  override def toString: String = {
           |    s"Celeborn version $$celebornVersion"
           |  }
           |}
           |""".stripMargin

      IO.write(targetFile, content)
      log.info(s"Generated CelebornBuildInfo at: $targetFile")

      Seq(targetFile)
    } dependsOn (Compile / PB.generate)).value,
    Compile / sourceGenerators += generateBuildInfo.taskValue
  )
}